### ISSUE TITLE
Models in DAE format do not work

### ISSUE THREAD

**Issue by meltingSnowdrift** [GER-Space/Kerbal-Konstructs#134]
It does not appear to be possible to add models from .dae format in KK. An entry shows up in the list of available static models, but no model shows up in the game scene when imported. An example of a case that behaves like this is attached. The DAE file was exported from Sketchup.

[Duck.zip](https://github.com/GER-Space/Kerbal-Konstructs/files/2877388/Duck.zip)

There seems to be conflicting information online about the usability of DAE format models in KSP. Are they actually correctly usable at all? If a technical fix on your side is infeasible, how can models in DAE format be converted to become insertable in KK?

**Comment by SpannerMonkey** [comment]
Hi DAE is an obsolete format. Its failure to load is because of changes made long ago in KSP,  it is not a BUG with KK or for that matter KSP.  
DAE models haven't been used since some when around KSP 0.20 at which time KSP moved from the partlab (squad supplied part editor) to a completely unity based import system, and at the same time overhauled  the editor , part cfg's and loading system. I think the last version to be able to load DAE files was KSP 0.90. The only currently supported file type that KSP can use is .Mu and the only way to successfully produce a .Mu file is to use the correct version of unity with the correct version of the squad supplied part tools , Current correct unity version is 2017.1.3p1
@GER-Space  not a bug can be closed

**Comment by theonegalen** [comment]
In addition to the unity + part tools option, there is a plug-in for blender that allows you to load and save .mu files.

https://forum.kerbalspaceprogram.com/index.php?/topic/40056-12-15-blender-280-mu-importexport-addon/
