### ISSUE TITLE
nullref by clicking other launchpads

### ISSUE THREAD

**Issue by yalov** [GER-Space/Kerbal-Konstructs#138]
Only happens after launch of the game — clicking other launchpads makes nullref several times, and then all ok 
https://streamable.com/5co11

**Comment by GER-Space** [comment]
can you please send me a KSP.log when you do that. I want to see what happens there.

**Comment by yalov** [comment]
https://www.dropbox.com/s/c2q8odmxlh7tucw/KSP.log?dl=0

**Comment by friznit** [comment]
This sounds related so I'll post logs here rather than open another ticket.  Using latest version of KK, attempting to launch from any pad other than stock throws an exception and the view returns to KSC.  Stock toolbar buttons are duplicated as well.

[ksp.log](https://drive.google.com/open?id=1E8yCPM2KW_uUF5BzX7WYR4nG58r1nevJ)
[output_log.txt](https://drive.google.com/open?id=1vU-rmiUvaLA1C6na3mReuMGF60rmLBu2)

I rolled back to the older version of KK and it works fine.

**Comment by GER-Space** [comment]
thanks, can you please test the following release? 
https://github.com/GER-Space/Kerbal-Konstructs/releases/tag/1.7.0.2

**Comment by GER-Space** [comment]
should be fixed
