### ISSUE TITLE
Vessel.Landed forced to true when launching into water

### ISSUE THREAD

**Issue by Gedas-S** [GER-Space/Kerbal-Konstructs#58]
When launching vessels straight into water with Kerbal Konstructs, Vessel.Landed is forced to true. (Both Vessel.Landed and Vessel.Splashed become true).

This causes issues for other mods, e.g. Vessel Mover will pick up the ship just fine, but when trying to place it back, it will think the ship is already landed, and just drop it instead of landing nicely.

Using KK version 1.2.0.4, KSP 1.3.1.1891, Win10 and [SpannerMonkey's](https://forum.kerbalspaceprogram.com/index.php?/profile/50907-spannermonkeysmce/) [SM_Static Harbors](https://www.dropbox.com/s/j073ubpar758yvy/SM_Static%20Condensed%20for%20release.zip?dl=0)

I suspect this might be a KSP thing, so not sure if a fix is feasible, but perhaps you'll have some ideas. :) Thanks!

**Comment by GER-Space** [comment]
Kk doesn't do anything with vessels or thier state. They are spawned normally at thier locations. I don't know why vessel mover has a bug with splashed vessels, but there is not much I could do against... At least I have no real clue what I should do. 
I would have to write vessel module which resets the state of a vessel when spawned from a water launch site... I think this is overkill, because vessel mover should change is behavior for splashed vessels.

**Comment by Gedas-S** [comment]
Fair enough. Seems this is KSP setting Vessel.Landed to true on launch then, nobody was expecting water launches when writing that piece of code. The full pattern is that KSP does not reset Vessel.Landed when leaving water, only when leaving land, so you end up with an airborne ship which still has Vessel.Landed = true. Which is probably a situation nobody should be expecting.

This came up for me when writing a different small thing, so I don't think it's a vessel mover bug either, it was just an example.

Thank you for the insights!
