### ISSUE TITLE
KCT can't get a list of open ports to move a craft

### ISSUE THREAD

**Issue by xilexio** [GER-Space/Kerbal-Konstructs#67]
There is one more incompatibility between latest Kerbal Construction Time and KK 1.3.0.3 - KK can't access correctly the list of open ports since changes after KK 1.2.0.4:
![image](https://user-images.githubusercontent.com/603874/37231575-f5aebebc-23eb-11e8-89fd-fe30aac0e025.png)

This is not a critical problem, since default launches from KSC still work, and it is possible to select the launch site in the KK menu in VAB/SPH when queuing a vehicle build. It is only not possible to move the craft after that using KCT's "Select LaunchSite".

Logs: 
[KSP.log](https://github.com/GER-Space/Kerbal-Konstructs/files/1798576/KSP.log)

**Comment by GER-Space** [comment]
Yes I see it now.. I must redo a change I wanted to keep... but I think I need to do it. 
At least with 1.4.X I don't have to care anymore as KTC can access the KSP launchsites and KK will register the open LaunchSites there too. This will make my live a lot easer.

I'll post a new version tomorrow. I need some sleep, as I had some strange problems with the LaunchSite selector that kept me busy all night.

**Comment by GER-Space** [comment]
I hope i got it right this time
https://github.com/GER-Space/Kerbal-Konstructs/releases/tag/1.3.0.4

**Comment by xilexio** [comment]
It works.

I wonder if official KSP got some of the ideas from KK + Kerbin Side. Anyway, I'll post new bugs (probably not KCT-related) if I find them. Sorry in advance.
Buildings being incorrectly placed, a tree from Terrain Scatter being in the middle of a runway go all to Kerbin Side issues, right? Also, I think I saw incorrect contents of Rocket fuel tank, but that was some time ago and I need to double check that in the current version.

**Comment by GER-Space** [comment]
I'm happy to hear. I'll post a new version soon, please check that aswell. 

I like also hear about the Kerbin-Side issues. Feel free to open issues you find: 

https://github.com/GER-Space/Kerbin-Side-Complete/issues

I did't change much about Kerbin-Side for now. So many issues exist since long before my time as AlphaAsh created the bases.
Trees showing up on some runways can only be removed now, because with 1.3 of KK I can remove the trees and alter some terrain. That why I'm eager to fix the bugs in this release, because its needed for everything I will do on Kerbin-Side

it would be a great help if you can check soon the next release of KK. I found some other bugs aswell (which must have existed for ages)

**Comment by GER-Space** [comment]
as this is fixed, i can close the issue
