### ISSUE TITLE
Add Launchpad Smoke!

### ISSUE THREAD

**Issue by damonvv** [GER-Space/Kerbal-Konstructs#87]
This is how I think the stock pads work:

Currently the stock pad has a few things added:
```
|--+PadFXReceiver T:LaunchpadFX L:30 (SurfaceFX)
|  |   Transform - PadFXReceiver
|  |   MeshFilter - PadFXReceiver
|  |   LaunchPadFX - PadFXReceiver
|  |   CollisionEventsHandler - PadFXReceiver
|  |   BoxCollider - PadFXReceiver
|  |   CollisionEventsHandler - PadFXReceiver
|  | 
|  |---PadSmokeLvl2 T:Untagged L:15 (Local Scenery)
|  |      Transform - PadSmokeLvl2
|  |      ParticleSystem - PadSmokeLvl2
|  |      ParticleSystemRenderer - PadSmokeLvl2
|  |    
|  |---PadSmokeLvl2 T:Untagged L:15 (Local Scenery)
|  |      Transform - PadSmokeLvl2
|  |      ParticleSystem - PadSmokeLvl2
|  |      ParticleSystemRenderer - PadSmokeLvl2
```
Right now with a `PadFXReceiver` tag to the object that is below the engines stops the smoke from getting all over the place, as showed [right here](https://cdn.discordapp.com/attachments/206472058228572162/411879858067734528/unknown.png):

It looks like KSP has 3 levels in which you can choose what type of smoke you want.
Those GameObjects are called `PadSmokeLvl1`, `PadSmokeLvl2` and `PadSmokeLvl3` as [seen here](https://cdn.discordapp.com/attachments/206472058228572162/411865530983645185/screenshot9.png).

I hope you can find a way to make my GameObject `PadSmokeLvl2` work with the currently working `PadFXReceiver`. Good luck!

**Comment by GER-Space** [comment]
I think the correct tag of the Receiver collider is "LaunchpadFX"

This will call the LaunchpadFX Module for the smoke animation. what I don't understand right now, how the right vector is used for the animation, because currently all smoke gies along the blue vector of the emiiter transforms. PadSmokeLvlXX (they are turned in the right direction)

**Comment by GER-Space** [comment]
Some more clarifications: 

The LaunchPadFX Module only triggers the registered ParticleSystems to emit some smoke particles. (and sets the strengs of the emission)
Sadly the LaunchPadFX module uses some protected members... I need to find some way to get the stock information our of it, because i need some stock smore material and the particle emitters need to setup correctly. 

For your LaunchPad:

1. the base plate collider needs the LaunchpadFX (I can set this when I have the name)
2. the emission points need to single transforms with the blue arrow pointing into the right direction. The names go later into the right config vaiable.

It will look like this: 

Module {
   moduleNamespace = KerbalKonstructs   // fixxed
   moduleClassname = LaunchPadFX         // fixed
   baseColliderName = CollectorPlate    // one Object should be enough
   SmikeEmitters = one, two, three, four  //CSV List support for diffrent names, also same name suported multiple times 
}

**Comment by GER-Space** [comment]
could you provide me with a download of your launchpad, that includes the Smoke emitter transform? I'll then test it until it is done.
